In [ ]:
## pandas is a powerful library for data manipulation and analysis in Python. It provides data structures like Series and DataFrame, which allow you to work with structured data efficiently. With pandas, you can easily handle missing data, perform group operations, and manipulate time series data. It also offers a wide range of functions for data cleaning, transformation, and visualization. Whether you're working with small datasets or large ones, pandas is an essential tool for any data analyst or scientist.

In [ ]:
import pandas as pd

In [ ]:
##PANDAS SERIES IS A ONE-DIMENSIONAL LABELED ARRAY CAPABLE OF HOLDING ANY DATA TYPE (INTEGERS, STRINGS, FLOATS, PYTHON OBJECTS, ETC.). IT IS SIMILAR TO A NUMPY ARRAY BUT WITH ADDITIONAL FUNCTIONALITY AND FLEXIBILITY. A SERIES CAN BE CREATED FROM A LIST, DICTIONARY, OR ANOTHER ARRAY-LIKE STRUCTURE. IT HAS AN INDEX THAT LABELS EACH ELEMENT IN THE SERIES, ALLOWING FOR EASY ACCESS AND MANIPULATION OF DATA. PANDAS SERIES ARE USEFUL FOR HANDLING AND ANALYZING DATA IN A VARIETY OF APPLICATIONS, INCLUDING TIME SERIES ANALYSIS, DATA CLEANING, AND STATISTICAL MODELING.

In [ ]:
import pandas as pd
data=[10,20,30,40,50]
series=pd.Series(data)
print(series)

In [ ]:
## create series from dictionary
data={'a':10,'b':20,'c':30}     ## a=key and 10=value that is assigned to key a
series=pd.Series(data)
print(series)

In [ ]:
data=[10,20,30]
index=['a','b','c']
series=pd.Series(data,index=index)
print(series)

In [ ]:
##dataframe is a two-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table, and it is one of the most commonly used data structures in pandas. A DataFrame can be created from various data sources, such as lists, dictionaries, or even other DataFrames. It provides powerful tools for data manipulation, including filtering, grouping, and aggregation. With DataFrames, you can easily handle and analyze large datasets, making it an essential tool for data scientists and analysts.

In [ ]:
## create dataframe from dictionary
data={'name':['Alice','Bob','Charlie'],'age':[25,30,35],'city':['New York','Los Angeles','Chicago']}
df=pd.DataFrame(data)
print(df)

In [ ]:
import numpy as np
np.array(df)

In [ ]:
## create a dataframe from a list of dictionaries

data=[{'name':'Alice','age':25,'city':'New York'},{'name':'Bob','age':30,'city':'Los Angeles'},{'name':'Charlie','age':35,'city':'Chicago'}]
df=pd.DataFrame(data)
print(df)


df.iloc[0]
df.loc[0][2]

In [ ]:
data

In [ ]:
df.loc[0]['city']

In [ ]:
df.at[0,'city']  ## access a single value for a row/column label pair using the at method, which is faster than loc for accessing a single value.

In [ ]:
df.at[2,'name']

In [ ]:
## accessing a specified elements using iat

df.iat[0,2]  ## access a single value for a row/column pair by integer position using the iat method, which is faster than iloc for accessing a single value.

In [ ]:
## data manupulation using pandas is a powerful tool for cleaning, transforming, and analyzing data. With pandas, you can easily handle missing data, filter and sort data, perform group operations, and create new columns based on existing ones. It also provides functions for merging and joining datasets, as well as for reshaping and pivoting data. Whether you're working with small datasets or large ones, pandas makes it easy to manipulate and analyze your data efficiently.

## using dataframes


df

In [49]:
df['salary']=[50000,60000,70000]
df

      name  age         city  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [44]:
# removing a column from dataframe

df.drop('salary',axis=1)  ## drop the salary column from the dataframe, axis=1 indicates that we want to drop a column (as opposed to a row), and inplace=True means that we want to modify the original dataframe rather than creating a new one.

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [48]:
df

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [50]:
df.drop('salary',axis=1,inplace=True)  ## dropping salary permanently from the dataframe
df

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [51]:
df.drop(0)

      name  age         city
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [52]:
df

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [56]:
  ## dropping the second row permanently from the dataframe
df.drop(1,inplace=True)
df

      name  age     city
2  Charlie   35  Chicago

In [70]:
df.head(2) ## returns the first n rows of the dataframe, where n is specified as an argument (default is 5).

      name  age     city
2  Charlie   35  Chicago

In [71]:
data

[{'name': 'Alice', 'age': 25, 'city': 'New York'},
 {'name': 'Bob', 'age': 30, 'city': 'Los Angeles'},
 {'name': 'Charlie', 'age': 35, 'city': 'Chicago'}]

In [74]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North